mqtt:
  broker: "localhost"
  port: 1883
  client_id: "thelia_heater"
  base_topic: "homeassistant/climate/thelia"
  discovery_prefix: "homeassistant"

ebus:
  device: "/dev/ttyS0"
  baudrate: 2400
  ebusctl_path: "/usr/bin/ebusctl"

heater:
  name: "Thelia Condens"
  manufacturer: "Saunier Duval"
  model: "30+"

logging:
  level: "INFO"
  file: "/var/log/ebus-thelia-condens-ha.log"